[package]
name = "digital-garden-steps"
version = "0.1.0"
authors = ["Christopher Biscardi <chris@christopherbiscardi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "digital_garden"
path = "src/lib.rs"

[[bin]]
name = "garden"
path = "src/main.rs"

[dependencies]
color-eyre = "0.5.10"
directories = "3.0.1"
edit = "0.1.2"
rprompt = "1.0.5"
slug = "0.1.4"
structopt = "0.3.21"

[dev-dependencies]
assert_cmd = "1.0.2"
assert_fs = "1.0.0"
predicates = "1.0.6"
